import Head from 'next/head';
import Image from 'next/image';
import Carousel from '../components/Carousel';
import Navbar from '../components/Navabr';
import styles from '../styles/Home.module.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Box, VStack } from '@chakra-ui/react';
import Hero from '../components/Hero';
import Gallery from '../components/Gallery';

export default function Home() {
  return (
    <Box w="100%" bg="brand.900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack minH="100vh" w="100%" overflow="hidden" h="auto" spacing={0}>
        <Navbar />
        <Carousel />
        <Gallery />
      </VStack>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Box>
  );
}
