import Head from 'next/head';
import Image from 'next/image';
import Carousel from '../components/Carousel';
import Navbar from '../components/Navabr';
import styles from '../styles/Home.module.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Box, VStack } from '@chakra-ui/react';
import Hero from '../components/Hero';
import Gallery from '../components/Gallery';
import Footer from '../components/Footer';
import HeroContact from '../components/HeroContact';
import Features from '../components/Features';

export default function Home() {
  return (
    <Box w="100%" bg="brand.900">
      <Head>
        <title>Restaurant Indian Spice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack minH="100vh" w="100%" overflow="hidden" h="auto" spacing={0}>
        <Navbar />
        <Carousel />
        <HeroContact />
        <Features />
        <Gallery />
      </VStack>
      <Footer />
    </Box>
  );
}
